### ISSUE TITLE
fill out README for Common Controls

### ISSUE THREAD

**Issue by afeld** [18F/tts-common-controls#3]
## Background Information

The Common Controls would be a good case for [README-Driven Development](https://tom.preston-werner.com/2010/08/23/readme-driven-development.html): working backwards from how we expect people to use them.

## Implementation Steps
- [ ] 

## Acceptance Criteria

- [x] Outlines the process for adding new components and how to validate them

**Comment by afeld** [comment]
[Working document](https://docs.google.com/document/d/1kGMoDacdM0oA8Io8hunQFaYnFTXr0aD7pDTlsPPNC0I/edit#heading=h.8feiujnl4t5y)

**Comment by adborden** [comment]
Data.gov uses this narrative for AC-2 (3):

> The TTS TechPortfolio configures user access for the AWS accounts in use by the SSB to be disabled after 90 days of inactivity.

**Comment by JJediny** [comment]
Basics set out in https://github.com/18F/tts-common-controls/pull/8
